name: Bug report
description: Report a problem with macblock
labels: [bug]
body:
  - type: textarea
    attributes:
      label: What happened?
      description: Describe the bug and what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Provide a minimal reproduction.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Diagnostics
      description: Paste the output of `macblock doctor` and any relevant logs.
      render: shell
    validations:
      required: false
  - type: input
    attributes:
      label: macOS version
      placeholder: "e.g. 14.6.1"
    validations:
      required: false
  - type: input
    attributes:
      label: macblock version
      placeholder: "e.g. 0.2.0"
    validations:
      required: false
